# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Wei Jing
tagline:             'After all, tomorrow is another day!'
description:         'Welcome, My Name is Wei Jing and I am web developer who living in New Zealand.'
url:                 http://wei.jing.ninja
baseurl:             'http://wei.jing.ninja'
paginate:            5

# About/contact
author:
  name:              Wei Jing
  url:               https://www.facebook.com/hydjing
  email:             jaychou123103@hotmail.com

# Custom vars
version:             1.0.0
