# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Wei Jing
tagline:             'Whatever is worth doing is worth doing well.'
description:         'Hi, My Name is Wei Jing and I am a web developer who living in New Zealand.'
url:                 http://wei.jing.ninja
baseurl:             'http://wei.jing.ninja'
paginate:            5

# About/contact
author:
  name:              Wei Jing
  url:               https://www.facebook.com/hydjing
  email:             jaychou123103@hotmail.com

# Custom vars
version:             1.1.0

#customized the blog path for posts
paginate_path: "/blog/page:num"
encoding: utf-8
highlighter: rouge 
